name: build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DotNet Setup
        uses: actions/setup-dotnet@v1

      - name: DotNet  Publish
        run: dotnet publish source/Web --configuration Release --output web

      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Angular Restore
        run: npm --prefix source/Web/Frontend run restore

      - name: Angular Build
        run: npm --prefix source/Web/Frontend run production

      - name: Prepare Artifact
        run: |
          rm -r web/*.pdb
          rm -r web/Frontend/*
          mv -f source/Web/Frontend/dist web/Frontend/dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: web
